name: CI Testing

on:
  pull_request:
    branches:
      - 'master'
      - 'main'

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  BUCKET_URL: ${{ secrets.BUCKET_URL }}
  RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup nodejs 20
        uses: actions/setup-node@v4
          with:
            node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
          with:
            version: 8
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm test